# 🛒 Python & Pandas: Shopping Dataset — Exploration & Cleaning
**Objective:** Learn Python basics and perform data exploration and cleaning using Pandas.

**Dataset:** E-Commerce Shopping Dataset (15 rows)

---
### Steps Covered
1. Load CSV into a Pandas DataFrame  
2. Explore data (head/tail, shape, columns, dtypes)  
3. Handle missing values (identify → fill / drop)  
4. Filter rows & select columns  
5. Remove duplicates  
6. Create a derived column (`total_amount = price × quantity`)  
7. Save the cleaned dataset as a new CSV

## Import Libraries

In [126]:
import pandas as pd
import numpy as np

print("Pandas version :", pd.__version__)
print("NumPy  version :", np.__version__)

Pandas version : 2.3.3
NumPy  version : 2.3.4

## 1. Load the CSV Dataset into a DataFrame
We use `pd.read_csv()` to load the raw shopping data file.

In [127]:
df = pd.read_csv('Ordered Data.csv')

print(f"Dataset loaded — {df.shape[0]} rows × {df.shape[1]} columns")
df

Dataset loaded — 15 rows × 9 columns

,order_id,customer_id,product,category,size,price,quantity,rating,purchase_date
0,ORD045,CUST1943,T-Shirt,Clothing,S,481.87,2.0,4.4,5/25/2023
1,ORD014,CUST1977,Watch,Accessories,M,919.52,9.0,2.1,2/18/2023
2,ORD099,CUST1501,T-Shirt,Clothing,S,110.50,8.0,2.3,4/13/2023
3,ORD071,CUST1606,Lamp,Home,NaN,1337.26,8.0,2.5,12/7/2023
4,ORD009,CUST4788,Tablet,Electronics,S,1354.32,NaN,3.0,7/16/2023
5,ORD041,CUST1678,Tablet,Electronics,M,653.61,3.0,4.1,3/9/2023
6,ORD018,CUST1785,Notebook,Books,NaN,218.77,6.0,3.8,6/22/2023
7,ORD076,CUST1388,Curtains,Home,L,1127.17,5.0,4.7,9/11/2023
8,ORD014,CUST1819,Shampoo,Beauty,S,115.33,9.0,2.9,11/30/2023
9,ORD010,CUST1977,Jacket,Clothing,L,1343.81,6.0,3.6,8/5/2023
10,ORD082,CUST1455,T-Shirt,Clothing,S,110.50,8.0,2.3,4/13/2023
11,ORD051,CUST1720,Running Shoes,Sports,M,890.50,4.0,4.5,10/19/2023
12,ORD077,CUST1672,Novel,Books,S,349.00,2.0,4.8,1/14/2023
13,ORD075,CUST1026,Lipstick,Beauty,XL,713.89,5.0,2.0,3/12/2023
14,ORD040,CUST1542,Shampoo,Beauty,NaN,890.00,3.0,4.6,7/28/2023

## 2. Explore the Data

In [128]:
# First 5 rows
print("HEAD (first 5 rows)")
df.head()

HEAD (first 5 rows)

,order_id,customer_id,product,category,size,price,quantity,rating,purchase_date
0,ORD045,CUST1943,T-Shirt,Clothing,S,481.87,2.0,4.4,5/25/2023
1,ORD014,CUST1977,Watch,Accessories,M,919.52,9.0,2.1,2/18/2023
2,ORD099,CUST1501,T-Shirt,Clothing,S,110.50,8.0,2.3,4/13/2023
3,ORD071,CUST1606,Lamp,Home,NaN,1337.26,8.0,2.5,12/7/2023
4,ORD009,CUST4788,Tablet,Electronics,S,1354.32,NaN,3.0,7/16/2023

In [129]:
# Last 5 rows
print("TAIL (last 5 rows)")
df.tail()

TAIL (last 5 rows)

,order_id,customer_id,product,category,size,price,quantity,rating,purchase_date
10,ORD082,CUST1455,T-Shirt,Clothing,S,110.50,8.0,2.3,4/13/2023
11,ORD051,CUST1720,Running Shoes,Sports,M,890.50,4.0,4.5,10/19/2023
12,ORD077,CUST1672,Novel,Books,S,349.00,2.0,4.8,1/14/2023
13,ORD075,CUST1026,Lipstick,Beauty,XL,713.89,5.0,2.0,3/12/2023
14,ORD040,CUST1542,Shampoo,Beauty,NaN,890.00,3.0,4.6,7/28/2023

In [130]:
# Shape, columns, dtypes
print("SHAPE")
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

print("\nCOLUMNS")
print(df.columns.tolist())

print("\nDATA TYPES :")
print(df.dtypes)

SHAPE
Rows: 15, Columns: 9

COLUMNS
['order_id', 'customer_id', 'product', 'category', 'size', 'price', 'quantity', 'rating', 'purchase_date']

DATA TYPES :
order_id          object
customer_id       object
product           object
category          object
size              object
price            float64
quantity         float64
rating           float64
purchase_date     object
dtype: object

In [131]:
# Statistical summary
print("DESCRIBE :")
df.describe()

DESCRIBE :

             price   quantity     rating
count    15.000000  14.000000  15.000000
mean    707.736667   5.571429   3.440000
std     462.327220   2.533295   1.043894
min     110.500000   2.000000   2.000000
25%     283.885000   3.250000   2.400000
50%     713.890000   5.500000   3.600000
75%    1023.345000   8.000000   4.450000
max    1354.320000   9.000000   4.800000

In [132]:
# Full info (non-null counts)
print("INFO :")
df.info()

INFO :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       15 non-null     object
 1   customer_id    15 non-null     object
 2   product        15 non-null     object
 3   category       15 non-null     object
 4   size           12 non-null     object
 5   price          15 non-null     float64
 6   quantity       14 non-null     float64
 7   rating         15 non-null     float64
 8   purchase_date  15 non-null     object
dtypes: float64(3), object(6)
memory usage: 1.2+ KB

## 3. Handle Missing Values
Identify nulls, then fill or drop them.

In [133]:
# Identify missing values
print("MISSING VALUES :")
missing = df.isnull().sum()
pct = (missing / len(df) * 100).round(1)
print(pd.DataFrame({'Count': missing, '%': pct})[missing > 0])
print(f"\nTotal missing cells: {df.isnull().sum().sum()}")

MISSING VALUES :
          Count     %
size          3  20.0
quantity      1   6.7

Total missing cells: 4

In [134]:
# Fill missing price with median
price_median = df['price'].median()
df['price'] = df['price'].fillna(price_median)
print(f"Filled missing 'price' with median → {price_median:.2f}")

# Fill missing quantity with mode (most common value)
qty_mode = df['quantity'].mode()[0]
df['quantity'] = df['quantity'].fillna(qty_mode)
print(f"Filled missing 'quantity' with mode → {qty_mode}")

# Fill missing size with 'Unknown'
df['size'] = df['size'].fillna('Unknown')
print("Filled missing 'size' with 'Unknown'")

Filled missing 'price' with median → 713.89
Filled missing 'quantity' with mode → 8.0
Filled missing 'size' with 'Unknown'

In [135]:
# Verify — should be 0
print(f"Remaining missing values: {df.isnull().sum().sum()}")
df.head()

Remaining missing values: 0

,order_id,customer_id,product,category,size,price,quantity,rating,purchase_date
0,ORD045,CUST1943,T-Shirt,Clothing,S,481.87,2.0,4.4,5/25/2023
1,ORD014,CUST1977,Watch,Accessories,M,919.52,9.0,2.1,2/18/2023
2,ORD099,CUST1501,T-Shirt,Clothing,S,110.50,8.0,2.3,4/13/2023
3,ORD071,CUST1606,Lamp,Home,Unknown,1337.26,8.0,2.5,12/7/2023
4,ORD009,CUST4788,Tablet,Electronics,S,1354.32,8.0,3.0,7/16/2023

## 4. Filter Rows & Select Columns
Use boolean indexing to extract meaningful subsets.

In [136]:
# Filter: rows where price > 500
print("Orders with price > 500")
df[df['price'] > 500][['order_id','product','category','price']]

Orders with price > 500

   order_id        product     category    price
1    ORD014          Watch  Accessories   919.52
3    ORD071           Lamp         Home  1337.26
4    ORD009         Tablet  Electronics  1354.32
5    ORD041         Tablet  Electronics   653.61
7    ORD076       Curtains        Home   1127.17
9    ORD010         Jacket     Clothing  1343.81
11   ORD051  Running Shoes       Sports   890.50
13   ORD075       Lipstick       Beauty   713.89
14   ORD040        Shampoo       Beauty   890.00

In [137]:
# Filter: specific categories using .isin()
print("Electronics & Beauty orders")
df[df['category'].isin(['Electronics','Beauty'])][['order_id','product','category','price','rating']]

Electronics & Beauty orders

   order_id   product     category    price  rating
4    ORD009    Tablet  Electronics  1354.32     3.0
5    ORD041    Tablet  Electronics   653.61     4.1
8    ORD014   Shampoo       Beauty   115.33     2.9
13   ORD075  Lipstick       Beauty   713.89     2.0
14   ORD040   Shampoo       Beauty   890.00     4.6

In [138]:
# Filter: high-rated products (rating >= 4.0)
print("High-rated products (rating >= 4.0)")
df[df['rating'] >= 4.0][['order_id','product','category','rating']]

High-rated products (rating >= 4.0)

   order_id        product     category  rating
0    ORD045        T-Shirt     Clothing     4.4
5    ORD041         Tablet  Electronics     4.1
7    ORD076       Curtains        Home      4.7
11   ORD051  Running Shoes       Sports     4.5
12   ORD077          Novel        Books     4.8
14   ORD040        Shampoo       Beauty     4.6

In [139]:
# Select specific columns only
print("Selected columns: order_id,product,price,quantity")
df[['order_id','product','price','quantity']]

Selected columns: order_id,product,price,quantity

   order_id        product    price  quantity
0    ORD045        T-Shirt   481.87       2.0
1    ORD014          Watch   919.52       9.0
2    ORD099        T-Shirt   110.50       8.0
3    ORD071           Lamp  1337.26       8.0
4    ORD009         Tablet  1354.32       8.0
5    ORD041         Tablet   653.61       3.0
6    ORD018       Notebook   218.77       6.0
7    ORD076       Curtains  1127.17       5.0
8    ORD014        Shampoo   115.33       9.0
9    ORD010         Jacket  1343.81       6.0
10   ORD082        T-Shirt   110.50       8.0
11   ORD051  Running Shoes   890.50       4.0
12   ORD077          Novel   349.00       2.0
13   ORD075       Lipstick   713.89       5.0
14   ORD040        Shampoo   890.00       3.0

## 5. Remove Duplicates

In [140]:
# Detect duplicates
print(f"Duplicate rows found: {df.duplicated().sum()}")
df[df.duplicated()]

Duplicate rows found: 0

Empty DataFrame
Columns: [order_id, customer_id, product, category, size, price, quantity, rating, purchase_date]
Index: []

In [141]:
# Drop duplicates
rows_before = len(df)
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)
print(f"Removed {rows_before - len(df)} duplicate(s)")
print(f"   Rows before : {rows_before}")
print(f"   Rows after  : {len(df)}")

Removed 0 duplicate(s)
   Rows before : 15
   Rows after  : 15

## 6. Create Derived Column: `total_amount`
**Formula:** `total_amount = price × quantity`

In [142]:
# Ensure correct dtypes first
df['price']    = pd.to_numeric(df['price'],    errors='coerce')
df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce').fillna(df['quantity'].mode()[0]).astype(int)

# Create derived column
df['total_amount'] = (df['price'] * df['quantity']).round(2)

print("Sample with total_amount ")
df[['order_id', 'product', 'price', 'quantity', 'total_amount']]

Sample with total_amount

   order_id        product    price  quantity  total_amount
0    ORD045        T-Shirt   481.87         2        963.74
1    ORD014          Watch   919.52         9       8275.68
2    ORD099        T-Shirt   110.50         8        884.00
3    ORD071           Lamp  1337.26         8      10698.08
4    ORD009         Tablet  1354.32         8      10834.56
5    ORD041         Tablet   653.61         3       1960.83
6    ORD018       Notebook   218.77         6       1312.62
7    ORD076       Curtains  1127.17         5       5635.85
8    ORD014        Shampoo   115.33         9       1037.97
9    ORD010         Jacket  1343.81         6       8062.86
10   ORD082        T-Shirt   110.50         8        884.00
11   ORD051  Running Shoes   890.50         4       3562.00
12   ORD077          Novel   349.00         2        698.00
13   ORD075       Lipstick   713.89         5       3569.45
14   ORD040        Shampoo   890.00         3       2670.00

In [143]:
# Quick stats on total_amount
print("total_amount Statistics")
print(df['total_amount'].describe().round(2))
print(f"\nTop revenue category:")
print(df.groupby('category')['total_amount'].sum().sort_values(ascending=False).round(2))

total_amount Statistics
count       15.00
mean      4069.98
std       3691.76
min        698.00
25%       1000.86
50%       2670.00
75%       6849.36
max      10834.56
Name: total_amount, dtype: float64

Top revenue category:
category
Electronics    12795.39
Clothing       10794.60
Home           10698.08
Accessories     8275.68
Beauty          7277.42
Home            5635.85
Sports          3562.00
Books           2010.62
Name: total_amount, dtype: float64

## 7. Save the Cleaned Dataset

In [144]:
output_path = 'Ordered cleaned Dataset.csv'
df.to_csv(output_path, index=False)
print(f" Cleaned dataset saved → '{output_path}'")
print(f" Final shape : {df.shape[0]} rows × {df.shape[1]} columns")

 Cleaned dataset saved → 'Ordered cleaned Dataset.csv'
 Final shape : 15 rows × 10 columns

---
## Summary

| Step | Action | Result |
|------|--------|--------|
| **Load** | `pd.read_csv()` | 15 rows × 9 columns loaded |
| **Explore** | `head/tail`, `shape`, `dtypes`, `describe()` | Understood structure & stats |
| **Missing Values** | Identified via `isnull().sum()` | price(1), quantity(1), size(3) nulls |
| **Fill/Drop** | Median for price, Mode for quantity, 'Unknown' for size | 0 nulls remaining |
| **Filter** | Boolean indexing & `.isin()` | Subsets extracted by price, category, rating |
| **Duplicates** | `duplicated()` + `drop_duplicates()` | 1 duplicate row removed → 14 rows |
| **Derived Column** | `total_amount = price × quantity` | Revenue insight per order |
| **Save** | `to_csv()` | `Ordered Cleaned Dataset.csv` written  |

### Key Pandas Methods Learned
- `pd.read_csv()` · `df.head()` · `df.tail()` · `df.shape` · `df.dtypes`
- `df.describe()` · `df.isnull()` · `fillna()` · `drop_duplicates()`
- Boolean filtering · `.isin()` · column arithmetic · `to_csv()`