# 🛒 Python & Pandas: Shopping Dataset — Exploration & Cleaning
**Objective:** Learn Python basics and perform data exploration and cleaning using Pandas.

**Dataset:** E-Commerce Shopping Dataset (15 rows)

---
### Steps Covered
1. Load CSV into a Pandas DataFrame  
2. Explore data (head/tail, shape, columns, dtypes)  
3. Handle missing values (identify → fill / drop)  
4. Filter rows & select columns  
5. Remove duplicates  
6. Create a derived column (`total_amount = price × quantity`)  
7. Save the cleaned dataset as a new CSV

## Step 0 — Import Libraries

In [ ]:
import pandas as pd
import numpy as np

print("Pandas version :", pd.__version__)
print("NumPy  version :", np.__version__)

Pandas version : 3.0.2
NumPy  version : 2.4.4

## Step 1 — Load the CSV Dataset into a DataFrame
We use `pd.read_csv()` to load the raw shopping data file.

In [2]:
df = pd.read_csv('shopping_data.csv')

print(f"✅ Dataset loaded — {df.shape[0]} rows × {df.shape[1]} columns")
df

✅ Dataset loaded — 15 rows × 9 columns

,order_id,customer_id,product,category,size,price,quantity,rating,purchase_date
0,ORD0073,CUST1606,Jacket,Clothing,S,481.87,2.0,4.4,2023-05-25
1,ORD0025,CUST1026,Shampoo,Beauty,L,919.52,9.0,2.1,2023-02-18
2,ORD0052,CUST1943,T-Shirt,Clothing,S,110.50,8.0,2.3,2023-04-13
3,ORD0171,CUST1977,Lamp,Home & Garden,NaN,1337.26,8.0,2.5,2023-12-07
4,ORD0099,CUST1672,Tablet,Electronics,S,1354.32,NaN,3.0,2023-07-16
5,ORD0041,CUST1234,Tablet,Electronics,M,653.61,3.0,4.1,2023-03-09
6,ORD0128,CUST1501,Cookbook,Books,NaN,218.77,6.0,3.8,2023-06-22
7,ORD0086,CUST1388,Curtains,Home & Garden,L,1127.17,5.0,4.7,2023-09-11
8,ORD0174,CUST1819,Shampoo,Beauty,S,115.33,9.0,2.9,2023-11-30
9,ORD0103,CUST1455,Headphones,Electronics,NaN,1343.81,6.0,3.6,2023-08-05
10,ORD0052,CUST1943,T-Shirt,Clothing,S,110.50,8.0,2.3,2023-04-13
11,ORD0061,CUST1720,Running Shoes,Sports,M,890.50,4.0,4.5,2023-10-19
12,ORD0047,CUST1303,Novel,Books,S,349.00,2.0,4.8,2023-01-14
13,ORD0155,CUST1867,Lipstick,Beauty,XL,713.89,5.0,2.0,2023-03-12
14,ORD0090,CUST1542,Dumbbells,Sports,NaN,890.00,3.0,4.6,2023-07-28

## Step 2 — Explore the Data

In [3]:
# First 5 rows
print("=== HEAD (first 5 rows) ===")
df.head()

=== HEAD (first 5 rows) ===

,order_id,customer_id,product,category,size,price,quantity,rating,purchase_date
0,ORD0073,CUST1606,Jacket,Clothing,S,481.87,2.0,4.4,2023-05-25
1,ORD0025,CUST1026,Shampoo,Beauty,L,919.52,9.0,2.1,2023-02-18
2,ORD0052,CUST1943,T-Shirt,Clothing,S,110.50,8.0,2.3,2023-04-13
3,ORD0171,CUST1977,Lamp,Home & Garden,NaN,1337.26,8.0,2.5,2023-12-07
4,ORD0099,CUST1672,Tablet,Electronics,S,1354.32,NaN,3.0,2023-07-16

In [4]:
# Last 5 rows
print("=== TAIL (last 5 rows) ===")
df.tail()

=== TAIL (last 5 rows) ===

,order_id,customer_id,product,category,size,price,quantity,rating,purchase_date
10,ORD0052,CUST1943,T-Shirt,Clothing,S,110.50,8.0,2.3,2023-04-13
11,ORD0061,CUST1720,Running Shoes,Sports,M,890.50,4.0,4.5,2023-10-19
12,ORD0047,CUST1303,Novel,Books,S,349.00,2.0,4.8,2023-01-14
13,ORD0155,CUST1867,Lipstick,Beauty,XL,713.89,5.0,2.0,2023-03-12
14,ORD0090,CUST1542,Dumbbells,Sports,NaN,890.00,3.0,4.6,2023-07-28

In [5]:
# Shape, columns, dtypes
print("=== SHAPE ===")
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

print("\n=== COLUMNS ===")
print(df.columns.tolist())

print("\n=== DATA TYPES ===")
print(df.dtypes)

=== SHAPE ===
Rows: 15, Columns: 9

=== COLUMNS ===
['order_id', 'customer_id', 'product', 'category', 'size', 'price', 'quantity', 'rating', 'purchase_date']

=== DATA TYPES ===
order_id             str
customer_id          str
product              str
category             str
size                 str
price            float64
quantity         float64
rating           float64
purchase_date        str
dtype: object

In [6]:
# Statistical summary
print("=== DESCRIBE ===")
df.describe()

=== DESCRIBE ===

             price   quantity     rating
count    15.000000  14.000000  15.000000
mean    707.736667   5.571429   3.440000
std     462.327220   2.533295   1.043894
min     110.500000   2.000000   2.000000
25%     283.885000   3.250000   2.400000
50%     713.890000   5.500000   3.600000
75%    1023.345000   8.000000   4.450000
max    1354.320000   9.000000   4.800000

In [7]:
# Full info (non-null counts)
print("=== INFO ===")
df.info()

=== INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       15 non-null     str
 1   customer_id    15 non-null     str
 2   product        15 non-null     str
 3   category       15 non-null     str
 4   size           11 non-null     str
 5   price          15 non-null     float64
 6   quantity       14 non-null     float64
 7   rating         15 non-null     float64
 8   purchase_date  15 non-null     str
dtypes: float64(3), str(6)
memory usage: 1.2 KB

## Step 3 — Handle Missing Values
Identify nulls, then fill or drop them.

In [8]:
# Identify missing values
print("=== MISSING VALUES ===")
missing = df.isnull().sum()
pct = (missing / len(df) * 100).round(1)
print(pd.DataFrame({'Count': missing, '%': pct})[missing > 0])
print(f"\nTotal missing cells: {df.isnull().sum().sum()}")

=== MISSING VALUES ===
          Count     %
size          4  26.7
quantity      1   6.7

Total missing cells: 5

In [9]:
# Fill missing price with median
price_median = df['price'].median()
df['price'] = df['price'].fillna(price_median)
print(f"✅ Filled missing 'price' with median → {price_median:.2f}")

# Fill missing quantity with mode (most common value)
qty_mode = df['quantity'].mode()[0]
df['quantity'] = df['quantity'].fillna(qty_mode)
print(f"✅ Filled missing 'quantity' with mode → {qty_mode}")

# Fill missing size with 'Unknown'
df['size'] = df['size'].fillna('Unknown')
print("✅ Filled missing 'size' with 'Unknown'")

✅ Filled missing 'price' with median → 713.89
✅ Filled missing 'quantity' with mode → 8.0
✅ Filled missing 'size' with 'Unknown'

In [10]:
# Verify — should be 0
print(f"Remaining missing values: {df.isnull().sum().sum()}")
df.head()

Remaining missing values: 0

,order_id,customer_id,product,category,size,price,quantity,rating,purchase_date
0,ORD0073,CUST1606,Jacket,Clothing,S,481.87,2.0,4.4,2023-05-25
1,ORD0025,CUST1026,Shampoo,Beauty,L,919.52,9.0,2.1,2023-02-18
2,ORD0052,CUST1943,T-Shirt,Clothing,S,110.50,8.0,2.3,2023-04-13
3,ORD0171,CUST1977,Lamp,Home & Garden,Unknown,1337.26,8.0,2.5,2023-12-07
4,ORD0099,CUST1672,Tablet,Electronics,S,1354.32,8.0,3.0,2023-07-16

## Step 4 — Filter Rows & Select Columns
Use boolean indexing to extract meaningful subsets.

In [11]:
# Filter: rows where price > 500
print("=== Orders with price > 500 ===")
df[df['price'] > 500][['order_id', 'product', 'category', 'price']]

=== Orders with price > 500 ===

   order_id        product       category    price
1   ORD0025        Shampoo         Beauty   919.52
3   ORD0171           Lamp  Home & Garden  1337.26
4   ORD0099         Tablet    Electronics  1354.32
5   ORD0041         Tablet    Electronics   653.61
7   ORD0086       Curtains  Home & Garden  1127.17
9   ORD0103     Headphones    Electronics  1343.81
11  ORD0061  Running Shoes         Sports   890.50
13  ORD0155       Lipstick         Beauty   713.89
14  ORD0090      Dumbbells         Sports   890.00

In [12]:
# Filter: specific categories using .isin()
print("=== Electronics & Beauty orders ===")
df[df['category'].isin(['Electronics', 'Beauty'])][['order_id', 'product', 'category', 'price', 'rating']]

=== Electronics & Beauty orders ===

   order_id     product     category    price  rating
1   ORD0025     Shampoo       Beauty   919.52     2.1
4   ORD0099      Tablet  Electronics  1354.32     3.0
5   ORD0041      Tablet  Electronics   653.61     4.1
8   ORD0174     Shampoo       Beauty   115.33     2.9
9   ORD0103  Headphones  Electronics  1343.81     3.6
13  ORD0155    Lipstick       Beauty   713.89     2.0

In [13]:
# Filter: high-rated products (rating >= 4.0)
print("=== High-rated products (rating >= 4.0) ===")
df[df['rating'] >= 4.0][['order_id', 'product', 'category', 'rating']]

=== High-rated products (rating >= 4.0) ===

   order_id        product       category  rating
0   ORD0073         Jacket       Clothing     4.4
5   ORD0041         Tablet    Electronics     4.1
7   ORD0086       Curtains  Home & Garden     4.7
11  ORD0061  Running Shoes         Sports     4.5
12  ORD0047          Novel          Books     4.8
14  ORD0090      Dumbbells         Sports     4.6

In [14]:
# Select specific columns only
print("=== Selected columns: order_id, product, price, quantity ===")
df[['order_id', 'product', 'price', 'quantity']]

=== Selected columns: order_id, product, price, quantity ===

   order_id        product    price  quantity
0   ORD0073         Jacket   481.87       2.0
1   ORD0025        Shampoo   919.52       9.0
2   ORD0052        T-Shirt   110.50       8.0
3   ORD0171           Lamp  1337.26       8.0
4   ORD0099         Tablet  1354.32       8.0
5   ORD0041         Tablet   653.61       3.0
6   ORD0128       Cookbook   218.77       6.0
7   ORD0086       Curtains  1127.17       5.0
8   ORD0174        Shampoo   115.33       9.0
9   ORD0103     Headphones  1343.81       6.0
10  ORD0052        T-Shirt   110.50       8.0
11  ORD0061  Running Shoes   890.50       4.0
12  ORD0047          Novel   349.00       2.0
13  ORD0155       Lipstick   713.89       5.0
14  ORD0090      Dumbbells   890.00       3.0

## Step 5 — Remove Duplicates

In [15]:
# Detect duplicates
print(f"Duplicate rows found: {df.duplicated().sum()}")
df[df.duplicated()]

Duplicate rows found: 1

,order_id,customer_id,product,category,size,price,quantity,rating,purchase_date
10,ORD0052,CUST1943,T-Shirt,Clothing,S,110.5,8.0,2.3,2023-04-13

In [16]:
# Drop duplicates
rows_before = len(df)
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)
print(f"✅ Removed {rows_before - len(df)} duplicate(s)")
print(f"   Rows before : {rows_before}")
print(f"   Rows after  : {len(df)}")

✅ Removed 1 duplicate(s)
   Rows before : 15
   Rows after  : 14

## Step 6 — Create Derived Column: `total_amount`
**Formula:** `total_amount = price × quantity`

In [17]:
# Ensure correct dtypes first
df['price']    = pd.to_numeric(df['price'],    errors='coerce')
df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce').fillna(df['quantity'].mode()[0]).astype(int)

# Create derived column
df['total_amount'] = (df['price'] * df['quantity']).round(2)

print("=== Sample with total_amount ===")
df[['order_id', 'product', 'price', 'quantity', 'total_amount']]

=== Sample with total_amount ===

   order_id        product    price  quantity  total_amount
0   ORD0073         Jacket   481.87         2        963.74
1   ORD0025        Shampoo   919.52         9       8275.68
2   ORD0052        T-Shirt   110.50         8        884.00
3   ORD0171           Lamp  1337.26         8      10698.08
4   ORD0099         Tablet  1354.32         8      10834.56
5   ORD0041         Tablet   653.61         3       1960.83
6   ORD0128       Cookbook   218.77         6       1312.62
7   ORD0086       Curtains  1127.17         5       5635.85
8   ORD0174        Shampoo   115.33         9       1037.97
9   ORD0103     Headphones  1343.81         6       8062.86
10  ORD0061  Running Shoes   890.50         4       3562.00
11  ORD0047          Novel   349.00         2        698.00
12  ORD0155       Lipstick   713.89         5       3569.45
13  ORD0090      Dumbbells   890.00         3       2670.00

In [18]:
# Quick stats on total_amount
print("=== total_amount Statistics ===")
print(df['total_amount'].describe().round(2))
print(f"\nTop revenue category:")
print(df.groupby('category')['total_amount'].sum().sort_values(ascending=False).round(2))

=== total_amount Statistics ===
count       14.00
mean      4297.55
std       3720.34
min        698.00
25%       1106.63
50%       3116.00
75%       7456.11
max      10834.56
Name: total_amount, dtype: float64

Top revenue category:
category
Electronics      20858.25
Home & Garden    16333.93
Beauty           12883.10
Sports            6232.00
Books             2010.62
Clothing          1847.74
Name: total_amount, dtype: float64

## Step 7 — Save the Cleaned Dataset

In [19]:
output_path = 'shopping_cleaned.csv'
df.to_csv(output_path, index=False)
print(f"✅ Cleaned dataset saved → '{output_path}'")
print(f"   Final shape : {df.shape[0]} rows × {df.shape[1]} columns")

✅ Cleaned dataset saved → 'shopping_cleaned.csv'
   Final shape : 14 rows × 10 columns

---
## 📋 Summary

| Step | Action | Result |
|------|--------|--------|
| **Load** | `pd.read_csv()` | 15 rows × 9 columns loaded |
| **Explore** | `head/tail`, `shape`, `dtypes`, `describe()` | Understood structure & stats |
| **Missing Values** | Identified via `isnull().sum()` | price(1), quantity(1), size(3) nulls |
| **Fill/Drop** | Median for price, Mode for quantity, 'Unknown' for size | 0 nulls remaining |
| **Filter** | Boolean indexing & `.isin()` | Subsets extracted by price, category, rating |
| **Duplicates** | `duplicated()` + `drop_duplicates()` | 1 duplicate row removed → 14 rows |
| **Derived Column** | `total_amount = price × quantity` | Revenue insight per order |
| **Save** | `to_csv()` | `shopping_cleaned.csv` written ✅ |

### Key Pandas Methods Learned
- `pd.read_csv()` · `df.head()` · `df.tail()` · `df.shape` · `df.dtypes`
- `df.describe()` · `df.isnull()` · `fillna()` · `drop_duplicates()`
- Boolean filtering · `.isin()` · column arithmetic · `to_csv()`